// GENERATED from Figma Variables — run npm run tokens:sync to update

export const containerTokens = {
  mobile: {
    input: {
      px: 24,
      py: 24,
    },
    digits: {
      px: 8,
      py: 16,
      gap: 2,
    },
    list: {
      px: 24,
      py: 16,
      pxRightLarge: 40,
      pyLarge: 24,
    },
    card: {
      px: 24,
      pyTopLarge: 32,
      pyTopSmall: 24,
      pyBottom: 24,
      gap: 16,
      textGap: 12,
      gapLarge: 24,
    },
    'interactionPressed-': {
      imgcardsOuterPx: 3,
      imgcardsOuterPy: 2,
      smallElementsPx: 2,
      smallElementsPy: 2,
      buttonHeight: 52,
      buttonPx: 4,
      largeElementsPx: 4,
      largeElementsPy: 4,
      cardsInnerPx: 20,
      cardsInnerPy: 20,
      pillInnerPx: 22,
    },
    button: {
      height: 56,
      pxPill: 40,
      gap: 8,
    },
    shortcutButton: {
      pxInner: 16,
      pyInner: 16,
      height: 56,
      pxPill: 24,
      pxOuter: 12,
      carouselGap: 8,
    },
    circleButton: {
      pxStandard: 16,
      pyStandard: 16,
      pxSmall: 12,
      pySmall: 12,
      pxLarge: 28,
      pyLarge: 28,
    },
    tag: {
      px: 24,
      gap: 8,
      height: 56,
    },
    text: {
      gap: 40,
      px: 24,
      smallGap: 12,
    },
    section: {
      gapStandard: 24,
      gapSmall: 8,
      pyButtom: 32,
      gapCardsStack: 40,
    },
    zone: {
      pyTop: 48,
      pyBottom: 64,
      gap: 48,
    },
    page: {
      pyTop: 80,
      pyPageBottom: 64,
      gap: -24,
    },
    height2: 56,
    topmodule: {
      forsideTop: 80,
      headerTop: 48,
      gap: 24,
      headerBottom: 64,
    },
  },
  tablet: {
    input: {
      px: 24,
      py: 24,
    },
    digits: {
      px: 8,
      py: 16,
      gap: 2,
    },
    list: {
      px: 32,
      py: 16,
      pxRightLarge: 48,
      pyLarge: 24,
    },
    card: {
      px: 24,
      pyTopLarge: 32,
      pyTopSmall: 24,
      pyBottom: 24,
      gap: 16,
      textGap: 12,
      gapLarge: 24,
    },
    'interactionPressed-': {
      imgcardsOuterPx: 4,
      imgcardsOuterPy: 3,
      smallElementsPx: 2,
      smallElementsPy: 2,
      buttonHeight: 52,
      buttonPx: 4,
      largeElementsPx: 4,
      largeElementsPy: 4,
      cardsInnerPx: 20,
      cardsInnerPy: 20,
      pillInnerPx: 22,
    },
    button: {
      height: 56,
      pxPill: 40,
      gap: 8,
    },
    shortcutButton: {
      pxInner: 24,
      pyInner: 24,
      height: 72,
      pxPill: 24,
      pxOuter: 4,
      carouselGap: 16,
    },
    circleButton: {
      pxStandard: 16,
      pyStandard: 16,
      pxSmall: 16,
      pySmall: 16,
      pxLarge: 28,
      pyLarge: 28,
    },
    tag: {
      px: 24,
      gap: 8,
      height: 56,
    },
    text: {
      gap: 40,
      px: 32,
      smallGap: 12,
    },
    section: {
      gapStandard: 24,
      gapSmall: 8,
      pyButtom: 32,
      gapCardsStack: 40,
    },
    zone: {
      pyTop: 64,
      pyBottom: 80,
      gap: 56,
    },
    page: {
      pyTop: 56,
      pyPageBottom: 0,
      gap: -24,
    },
    height2: 0,
    topmodule: {
      forsideTop: 56,
      headerTop: 48,
      gap: 32,
      headerBottom: 64,
    },
  },
  desktop: {
    input: {
      px: 24,
      py: 24,
    },
    digits: {
      px: 8,
      py: 16,
      gap: 2,
    },
    list: {
      px: 32,
      py: 16,
      pxRightLarge: 48,
      pyLarge: 24,
    },
    card: {
      px: 24,
      pyTopLarge: 32,
      pyTopSmall: 24,
      pyBottom: 24,
      gap: 16,
      textGap: 12,
      gapLarge: 24,
    },
    'interactionPressed-': {
      imgcardsOuterPx: 4,
      imgcardsOuterPy: 3,
      smallElementsPx: 2,
      smallElementsPy: 2,
      buttonHeight: 52,
      buttonPx: 4,
      largeElementsPx: 4,
      largeElementsPy: 4,
      cardsInnerPx: 20,
      cardsInnerPy: 20,
      pillInnerPx: 22,
    },
    button: {
      height: 56,
      pxPill: 40,
      gap: 8,
    },
    shortcutButton: {
      pxInner: 24,
      pyInner: 24,
      height: 72,
      pxPill: 24,
      pxOuter: 4,
      carouselGap: 16,
    },
    circleButton: {
      pxStandard: 16,
      pyStandard: 16,
      pxSmall: 16,
      pySmall: 16,
      pxLarge: 28,
      pyLarge: 28,
    },
    tag: {
      px: 24,
      gap: 8,
      height: 56,
    },
    text: {
      gap: 40,
      px: 32,
      smallGap: 12,
    },
    section: {
      gapStandard: 24,
      gapSmall: 8,
      pyButtom: 32,
      gapCardsStack: 40,
    },
    zone: {
      pyTop: 64,
      pyBottom: 80,
      gap: 56,
    },
    page: {
      pyTop: 72,
      pyPageBottom: 0,
      gap: -24,
    },
    height2: 0,
    topmodule: {
      forsideTop: 56,
      headerTop: 48,
      gap: 32,
      headerBottom: 64,
    },
  },
} as const;

export type ContainerTokens = typeof containerTokens;
