// GENERATED from Figma Variables — run npm run tokens:sync to update

export const typographyTokens = {
  mobile: {
    displayL: {
      size: 56,
      lineheight: 56,
      letterspacing: -0.25,
      weight: "Light",
    },
    lS: {
      none: 0,
      l: 0.5,
      s: 0.20000000298023224,
      xXS: 0.10000000149011612,
      xXXS: -0.25,
      m: 0.4000000059604645,
      xS: 0.15000000596046448,
    },
    base: {
      font: "Mari",
      regular: "Regular",
      book: "Book",
      bold: "Bold",
      light: "Light",
      poster: "Poster",
    },
    displayM: {
      size: 44,
      lineheight: 44,
      letterspacing: -0.25,
      weight: "Light",
    },
    displayS: {
      size: 36,
      lineheight: 36,
      letterspacing: -0.25,
      weight: "Light",
    },
    headlineL: {
      size: 40,
      lineheight: 40,
      letterspacing: -0.25,
      weight: "Regular",
    },
    headlineM: {
      size: 32,
      lineheight: 35,
      letterspacing: -0.25,
      weight: "Regular",
    },
    titleL: {
      size: 26,
      lineheight: 28,
      letterspacing: 0,
      weight: "Regular",
    },
    titleM: {
      size: 22,
      lineheight: 20,
      letterspacing: 0.15000000596046448,
      weight: "Regular",
    },
    titleS: {
      size: 18,
      lineheight: 18,
      letterspacing: 0.10000000149011612,
      weight: "Bold",
    },
    titleSEmphasis: {
      size: 18,
      lineheight: 18,
      letterspacing: 0.10000000149011612,
      weight: "Poster",
    },
    titleXS: {
      size: 16,
      lineheight: 16,
      letterspacing: 0.10000000149011612,
      weight: "Bold",
    },
    titleXSEmphasis: {
      size: 16,
      lineheight: 16,
      letterspacing: 0.10000000149011612,
      weight: "Poster",
    },
    bodyL: {
      size: 20,
      lineheight: 26,
      letterspacing: 0.4000000059604645,
      weight: "Book",
    },
    bodyM: {
      size: 18,
      lineheight: 23.5,
      letterspacing: 0.5,
      weight: "Book",
    },
    bodyS: {
      size: 16,
      lineheight: 21,
      letterspacing: 0.5,
      weight: "Book",
    },
    description: {
      size: 16,
      lineheight: 17.5,
      letterspacing: 0.20000000298023224,
      weight: "Regular",
    },
    descriptionTiny: {
      size: 14,
      lineheight: 15.5,
      letterspacing: 0.5,
      weight: "Book",
    },
    label: {
      size: 20,
      lineheight: 20,
      letterspacing: 0.10000000149011612,
      weight: "Regular",
    },
    headlineMEmphasis: {
      size: 32,
      lineheight: 29,
      letterspacing: 0.10000000149011612,
      weight: "Poster",
    },
    buttons: {
      size: 16,
      lineheight: 17.5,
      letterspacing: 0.20000000298023224,
      weight: "Regular",
    },
    displayMEmphasis: {
      size: 44,
      lineheight: 44,
      letterspacing: 0.10000000149011612,
      weight: "Poster",
    },
    fontWeightsRN: {
      regular: "400",
      book: "300",
      bold: "700",
      light: "300",
      poster: "900",
    },
  },
  tablet: {
    displayL: {
      size: 64,
      lineheight: 64,
      letterspacing: 0,
      weight: "Light",
    },
    lS: {
      none: 0,
      l: 0,
      s: 0,
      xXS: 0,
      xXXS: 0,
      m: 0,
      xS: 0,
    },
    base: {
      font: "Mari",
      regular: "Regular",
      book: "Book",
      bold: "Bold",
      light: "Light",
      poster: "Poster",
    },
    displayM: {
      size: 52,
      lineheight: 52,
      letterspacing: 0,
      weight: "Light",
    },
    displayS: {
      size: 42,
      lineheight: 42,
      letterspacing: 0,
      weight: "Light",
    },
    headlineL: {
      size: 44,
      lineheight: 44,
      letterspacing: 0,
      weight: "Regular",
    },
    headlineM: {
      size: 36,
      lineheight: 40,
      letterspacing: 0,
      weight: "Regular",
    },
    titleL: {
      size: 28,
      lineheight: 31,
      letterspacing: 0,
      weight: "Regular",
    },
    titleM: {
      size: 24,
      lineheight: 22,
      letterspacing: 0,
      weight: "Regular",
    },
    titleS: {
      size: 20,
      lineheight: 20,
      letterspacing: 0,
      weight: "Bold",
    },
    titleSEmphasis: {
      size: 20,
      lineheight: 20,
      letterspacing: 0,
      weight: "Poster",
    },
    titleXS: {
      size: 17,
      lineheight: 17,
      letterspacing: 0,
      weight: "Bold",
    },
    titleXSEmphasis: {
      size: 17,
      lineheight: 17,
      letterspacing: 0,
      weight: "Poster",
    },
    bodyL: {
      size: 22,
      lineheight: 28,
      letterspacing: 0,
      weight: "Book",
    },
    bodyM: {
      size: 19,
      lineheight: 25,
      letterspacing: 0,
      weight: "Book",
    },
    bodyS: {
      size: 17,
      lineheight: 22,
      letterspacing: 0,
      weight: "Book",
    },
    description: {
      size: 17,
      lineheight: 19,
      letterspacing: 0,
      weight: "Regular",
    },
    descriptionTiny: {
      size: 15,
      lineheight: 16.5,
      letterspacing: 0,
      weight: "Book",
    },
    label: {
      size: 21,
      lineheight: 21,
      letterspacing: 0,
      weight: "Regular",
    },
    headlineMEmphasis: {
      size: 36,
      lineheight: 32,
      letterspacing: 0,
      weight: "Poster",
    },
    buttons: {
      size: 17,
      lineheight: 19,
      letterspacing: 0,
      weight: "Regular",
    },
    displayMEmphasis: {
      size: 52,
      lineheight: 52,
      letterspacing: 0,
      weight: "Poster",
    },
    fontWeightsRN: {
      regular: "400",
      book: "300",
      bold: "700",
      light: "300",
      poster: "900",
    },
  },
  desktop: {
    displayL: {
      size: 72,
      lineheight: 72,
      letterspacing: 0,
      weight: "Light",
    },
    lS: {
      none: 0,
      l: 0,
      s: 0,
      xXS: 0,
      xXXS: 0,
      m: 0,
      xS: 0,
    },
    base: {
      font: "Mari",
      regular: "Regular",
      book: "Book",
      bold: "Bold",
      light: "Light",
      poster: "Poster",
    },
    displayM: {
      size: 60,
      lineheight: 60,
      letterspacing: 0,
      weight: "Light",
    },
    displayS: {
      size: 48,
      lineheight: 48,
      letterspacing: 0,
      weight: "Light",
    },
    headlineL: {
      size: 48,
      lineheight: 48,
      letterspacing: 0,
      weight: "Regular",
    },
    headlineM: {
      size: 40,
      lineheight: 44,
      letterspacing: 0,
      weight: "Regular",
    },
    titleL: {
      size: 32,
      lineheight: 35,
      letterspacing: 0,
      weight: "Regular",
    },
    titleM: {
      size: 26,
      lineheight: 24,
      letterspacing: 0,
      weight: "Regular",
    },
    titleS: {
      size: 22,
      lineheight: 22,
      letterspacing: 0,
      weight: "Bold",
    },
    titleSEmphasis: {
      size: 22,
      lineheight: 22,
      letterspacing: 0,
      weight: "Poster",
    },
    titleXS: {
      size: 18,
      lineheight: 18,
      letterspacing: 0,
      weight: "Bold",
    },
    titleXSEmphasis: {
      size: 18,
      lineheight: 18,
      letterspacing: 0,
      weight: "Poster",
    },
    bodyL: {
      size: 24,
      lineheight: 31,
      letterspacing: 0,
      weight: "Book",
    },
    bodyM: {
      size: 20,
      lineheight: 26,
      letterspacing: 0,
      weight: "Book",
    },
    bodyS: {
      size: 18,
      lineheight: 23.5,
      letterspacing: 0,
      weight: "Book",
    },
    description: {
      size: 18,
      lineheight: 20,
      letterspacing: 0,
      weight: "Regular",
    },
    descriptionTiny: {
      size: 16,
      lineheight: 17.5,
      letterspacing: 0,
      weight: "Book",
    },
    label: {
      size: 22,
      lineheight: 22,
      letterspacing: 0,
      weight: "Regular",
    },
    headlineMEmphasis: {
      size: 40,
      lineheight: 36,
      letterspacing: 0,
      weight: "Poster",
    },
    buttons: {
      size: 18,
      lineheight: 20,
      letterspacing: 0,
      weight: "Regular",
    },
    displayMEmphasis: {
      size: 60,
      lineheight: 60,
      letterspacing: 0,
      weight: "Poster",
    },
    fontWeightsRN: {
      regular: "400",
      book: "300",
      bold: "700",
      light: "300",
      poster: "900",
    },
  },
} as const;

export type TypographyTokens = typeof typographyTokens;
