name: Create Production Builds

on:
  push:
    branches: ["main"]
    tags: ["v1*", "v2*", "v3*"]
    paths:
      - !applications/mary-ui-app/**

jobs:
  build_android:
    type: build # This job type creates a production build for Android
    params:
      platform: android
  build_ios:
    type: build # This job type creates a production build for iOS
    params:
      platform: ios
