name: Create Production Builds

on:
  push:
    branches: ["main"]
    tags: ["mary-guiden-v1*", "mary-guiden-v2*", "mary-guiden-v3*"]
    paths:
      - !applications/mary-ui-app/**

jobs:
  build_android:
    type: build # This job type creates a production build for Android
    params:
      platform: android
  build_ios:
    type: build # This job type creates a production build for iOS
    params:
      platform: ios
