name: Storybook Build and Publish

on:
    push:
        branches:
            - main
        paths:
            - lib/**
            - .github/**
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        env:
            REGISTRY: ghcr.io
            REPO_NAME: ${{ github.repository }}
        outputs:
            image-tag: ${{ steps.export-tag.outputs.image-tag }}
        steps:
            - name: Log in to container registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Validate production dependency split
              run: npm ci --workspace=lib --include-workspace-root=false --omit=dev --no-audit --no-fund

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  tags: |
                      ghcr.io/mary-initial/mary-initial-frontend/storybook:latest
                      ghcr.io/mary-initial/mary-initial-frontend/storybook:build-${{ github.run_number }}
                  cache-from: "type=registry,ref=ghcr.io/mary-initial/mary-initial-frontend/storybook:cache"
                  cache-to: "type=registry,ref=ghcr.io/mary-initial/mary-initial-frontend/storybook:cache"
                  platforms: linux/amd64
                  context: .
                  file: storybook.dockerfile

            - name: Export image tag
              id: export-tag
              run: echo "image-tag=build-${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT
